git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: required
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_NDK_REVISION=r13

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_BUILD_TOOLS_VERSION
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-android-$ANDROID_BUILD_TOOLS_VERSION
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-.+'

before_install:
  # By default, we get an older version of libstdc++6 so we need to update it
  # http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6

  - echo y | android update sdk --no-ui --filter build-tools-${ANDROID_BUILD_TOOLS_VERSION},android-${ANDROID_API_LEVEL},extra-android-m2repository
  - wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_REVISION}-linux-x86_64.zip -O ndk.zip
  - unzip ndk.zip -d . > /dev/null
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-${ANDROID_NDK_REVISION}
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

  - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
  - chmod +x install-cmake.sh
  - bash ./install-cmake.sh

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

