git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-.+'

before_install:
  - echo y | android update sdk --no-ui --filter build-tools-24.0.3,android-24,extra-android-m2repository
  - wget https://dl.google.com/android/repository/android-ndk-r13-linux-x86_64.zip -O ndk.zip
  - unzip ndk.zip -d . > /dev/null
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r13
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -O cmake.tar.gz
  - mkdir -p /usr/local/android-sdk
  - tar -xf cmake.tar.gz -C /usr/local/android-sdk
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
