git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-.+'

before_install:
  - wget https://dl.google.com/android/repository/android-ndk-r13-linux-x86_64.zip -O ndk.tgz
  - tar -xf ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
  - echo y | android update sdk --no-ui --filter build-tools-24.0.3,android-24,extra-android-m2repository
