git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-.+'

 before_install:
  - echo y | android update sdk --no-ui --filter build-tools-24.0.3,android-24,extra-android-m2repository
  
