git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-support
  licenses:
    - '.+'

before_install:
 - echo y | android update sdk --no-ui --filter build-tools-24.0.0,android-24,extra-android-m2repository
