git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

