git:
  depth: 1

branches:
  only:
    - master

jdk: oraclejdk8
language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-support
  licenses:
    - '.+'

